# Generated by Django 6.0.3 on 2026-03-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Ollama AI', max_length=100)),
                ('website_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('website_favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('website_description', models.TextField(default='A powerful AI chatbot platform built with Django and Ollama API.')),
                ('maintainance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
