# Generated by Django 6.0.3 on 2026-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversations',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatconversations',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
