# Generated by Django 6.0.3 on 2026-03-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chatconversations_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vision/images/'),
        ),
    ]
