# Generated by Django 6.0.3 on 2026-04-05 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_legacy_owner(apps, schema_editor):
    user_model_label = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_model_label[0], user_model_label[1])
    ChatSession = apps.get_model("app", "ChatSession")

    if not ChatSession.objects.filter(owner__isnull=True).exists():
        return

    base_username = "legacy-private-sessions"
    username = base_username
    suffix = 1
    while User.objects.filter(username=username).exists():
        username = f"{base_username}-{suffix}"
        suffix += 1

    # Historical migration models do not expose helper methods like
    # set_unusable_password(), so assign an unusable hash directly.
    legacy_user = User(username=username, email="", password="!")
    legacy_user.is_active = False
    legacy_user.save()

    ChatSession.objects.filter(owner__isnull=True).update(owner=legacy_user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_alter_websitesettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_legacy_owner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chatsession",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["owner", "-updated_at"], name="app_chatses_owner_i_79aaa6_idx"),
        ),
    ]
