# Generated by Django 6.0.3 on 2026-03-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chatconversations_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'Website Settings'},
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='system_prompt',
            field=models.TextField(blank=True, default="You are a helpful and precise assistant for answering user queries. Always use all available information to provide the best answer. If you don't know the answer, say you don't know. Be concise and clear in your responses."),
        ),
        migrations.AddIndex(
            model_name='chatconversations',
            index=models.Index(fields=['session', '-created_at'], name='app_chatcon_session_891e5c_idx'),
        ),
    ]
